using System;
using System.IO;
using System.Text;
using OxenteGames.JiraCommunication.Agents;
using OxenteGames.JiraCommunication.Settings;

namespace OxenteGames.JiraCommunication.Skills
{
    internal struct SkillInstallResult
    {
        public bool Success;
        public string Path;
        public string Error;
    }

    /// <summary>
    /// Writes the project's agent instructions for one provider.
    /// </summary>
    /// <remarks>
    /// Each provider reads project instructions from a different place, and one of
    /// them is a file the team also edits by hand, so writers must differ in more than
    /// a filename.
    /// </remarks>
    internal interface ISkillWriter
    {
        string Provider { get; }

        /// <summary>Path this writer owns, relative to the repository root.</summary>
        string RelativePath { get; }

        SkillInstallResult Write(string repositoryRoot, string body);
    }

    /// <summary>
    /// Generates and installs the project's agent instructions.
    /// </summary>
    /// <remarks>
    /// The package is the source of truth for these instructions. Keeping them
    /// generated rather than hand-maintained means the branch and commit templates the
    /// agent is told to follow are the ones actually configured in the Jira window,
    /// instead of a copy that silently drifts.
    /// <para>
    /// Deliberately absent: any Jira credential. The generated instructions tell the
    /// agent that Jira reads and writes happen in the Unity window, which already
    /// holds the token. An agent that cannot reach Jira cannot leak the token, and it
    /// does not need Jira access to do the code work anyway.
    /// </para>
    /// </remarks>
    internal static class SkillInstaller
    {
        public const string SkillName = "jira-unity";

        private const string BlockBegin = "<!-- jira-unity:begin (generated by the Jira package — do not edit) -->";
        private const string BlockEnd = "<!-- jira-unity:end -->";

        public static ISkillWriter WriterFor(string provider)
        {
            return provider == AgentProvider.Codex
                ? (ISkillWriter)new CodexSkillWriter()
                : new ClaudeSkillWriter();
        }

        public static SkillInstallResult Install(string provider, string repositoryRoot)
        {
            if (string.IsNullOrWhiteSpace(repositoryRoot) || !Directory.Exists(repositoryRoot))
            {
                return new SkillInstallResult
                {
                    Success = false,
                    Error = "no-repository"
                };
            }

            ISkillWriter writer = WriterFor(provider);
            return writer.Write(repositoryRoot, BuildBody(provider));
        }

        /// <summary>Absolute path a provider's instructions would be written to.</summary>
        public static string ResolvePath(string provider, string repositoryRoot)
        {
            if (string.IsNullOrWhiteSpace(repositoryRoot))
                return string.Empty;

            return Path.Combine(repositoryRoot, WriterFor(provider).RelativePath);
        }

        public static bool IsInstalled(string provider, string repositoryRoot)
        {
            string path = ResolvePath(provider, repositoryRoot);
            if (string.IsNullOrWhiteSpace(path) || !File.Exists(path))
                return false;

            try
            {
                // For a shared file, presence is not enough — our block must be there.
                if (provider == AgentProvider.Codex)
                    return File.ReadAllText(path).Contains(BlockBegin);

                return true;
            }
            catch (Exception)
            {
                return false;
            }
        }

        /// <summary>
        /// The instruction body, shared by both providers. Only the surrounding file
        /// format differs between them.
        /// </summary>
        public static string BuildBody(string provider)
        {
            string branchTemplate = JiraPreferences.GitBranchTemplate;
            string commitTemplate = JiraPreferences.GitCommitTemplate;
            string baseBranch = JiraPreferences.GitBaseBranch;

            var sb = new StringBuilder(2048);

            sb.AppendLine("## Working on Jira issues in this Unity project");
            sb.AppendLine();
            sb.AppendLine("Tasks reach you from the Jira Workspace window inside the Unity Editor.");
            sb.AppendLine("The prompt carries the issue key, summary and description; you have the");
            sb.AppendLine("repository. Read the referenced code before proposing a change.");
            sb.AppendLine();

            sb.AppendLine("### Branch and commit conventions");
            sb.AppendLine();
            sb.AppendLine("- Branch template: `" + branchTemplate + "`");
            sb.AppendLine("- Commit template: `" + commitTemplate + "`");
            sb.AppendLine("- Base branch: `" + baseBranch + "`");
            sb.AppendLine("- Placeholders: `{type}` is a Conventional Commit type (feat, fix, chore, ...),");
            sb.AppendLine("  `{key}` is the Jira issue key, `{slug}` is the slugged summary, `{title}` the summary.");
            sb.AppendLine();
            sb.AppendLine("Do not commit, push, or create pull requests unless the task explicitly asks.");
            sb.AppendLine("The Editor already offers a one-click branch and commit-message action, so an");
            sb.AppendLine("unrequested commit competes with what the developer is doing.");
            sb.AppendLine();

            sb.AppendLine("### Jira itself");
            sb.AppendLine();
            sb.AppendLine("Your environment may carry `JIRA_URL`, `JIRA_EMAIL` and `JIRA_API_TOKEN`, from");
            sb.AppendLine("the project's `.env`. When all three are set you may query the Jira Cloud REST");
            sb.AppendLine("API yourself for context you are missing — the issue, its comments, linked");
            sb.AppendLine("issues — with basic auth:");
            sb.AppendLine();
            sb.AppendLine("```sh");
            sb.AppendLine("curl -s -u \"$JIRA_EMAIL:$JIRA_API_TOKEN\" \\");
            sb.AppendLine("  \"$JIRA_URL/rest/api/3/issue/KEY-123?fields=summary,description,status\"");
            sb.AppendLine("```");
            sb.AppendLine();
            sb.AppendLine("Rules for that access:");
            sb.AppendLine();
            sb.AppendLine("- Reading is free. **Writing** — transitions, comments, edits — only when the");
            sb.AppendLine("  task explicitly asks. The developer normally does those in the Jira Workspace");
            sb.AppendLine("  window, and an unrequested transition fights whatever they are doing there.");
            sb.AppendLine("- Never echo the token, and never write it into a file, a commit or your answer.");
            sb.AppendLine("- When a variable is missing, say so instead of guessing a URL: the developer");
            sb.AppendLine("  fills them in under Settings > Agent environment in the Unity window.");
            sb.AppendLine();

            sb.AppendLine("### Unity specifics");
            sb.AppendLine();
            sb.AppendLine("- Every asset has a sibling `.meta` file holding its GUID. Deleting or renaming");
            sb.AppendLine("  an asset means handling its `.meta` too, or references break.");
            sb.AppendLine("- Prefabs, scenes and assets are YAML keyed by fileID and GUID. Hand-editing is");
            sb.AppendLine("  possible but unforgiving; prefer editing code, and be explicit when you must");
            sb.AppendLine("  touch a `.prefab`, `.unity` or `.asset` file.");
            sb.AppendLine("- `Library/`, `Temp/`, `Logs/` and `obj/` are generated. Never edit or commit them.");
            sb.AppendLine("- Editor-only code belongs under an `Editor/` folder or an Editor assembly");
            sb.AppendLine("  definition; referencing `UnityEditor` from runtime code breaks player builds.");
            sb.AppendLine("- You cannot compile or run the project: the Editor owns that. Do not claim a");
            sb.AppendLine("  change compiles. Say what you changed and what the developer should verify.");
            sb.AppendLine();

            sb.AppendLine("### Reporting back");
            sb.AppendLine();
            sb.AppendLine("Your final message is shown in the Unity window as the run's result, so make it");
            sb.AppendLine("the summary the developer needs: what changed, which files, what to verify, and");
            sb.AppendLine("anything you deliberately left out.");

            if (provider == AgentProvider.Codex)
            {
                sb.AppendLine();
                sb.AppendLine("Runs launched from Unity are non-interactive: you cannot ask a follow-up");
                sb.AppendLine("question mid-run. When a task is ambiguous, state the assumption you took.");
            }

            return sb.ToString();
        }

        /// <summary>Replaces our managed block in shared content, or appends it.</summary>
        internal static string MergeManagedBlock(string existing, string body)
        {
            string block = BlockBegin + Environment.NewLine + body.TrimEnd() + Environment.NewLine + BlockEnd;

            if (string.IsNullOrWhiteSpace(existing))
                return block + Environment.NewLine;

            int begin = existing.IndexOf(BlockBegin, StringComparison.Ordinal);
            int end = existing.IndexOf(BlockEnd, StringComparison.Ordinal);

            if (begin >= 0 && end > begin)
            {
                // Replace in place so anything the team wrote around it is preserved.
                string before = existing.Substring(0, begin);
                string after = existing.Substring(end + BlockEnd.Length);
                return before + block + after;
            }

            string separator = existing.EndsWith(Environment.NewLine, StringComparison.Ordinal)
                ? Environment.NewLine
                : Environment.NewLine + Environment.NewLine;

            return existing + separator + block + Environment.NewLine;
        }
    }

    /// <summary>Writes a Claude Code skill: a directory we fully own.</summary>
    internal sealed class ClaudeSkillWriter : ISkillWriter
    {
        public string Provider => AgentProvider.ClaudeCode;

        public string RelativePath =>
            Path.Combine(Path.Combine(Path.Combine(".claude", "skills"), SkillInstaller.SkillName), "SKILL.md");

        public SkillInstallResult Write(string repositoryRoot, string body)
        {
            try
            {
                string path = Path.Combine(repositoryRoot, RelativePath);
                Directory.CreateDirectory(Path.GetDirectoryName(path));

                var sb = new StringBuilder(body.Length + 512);

                // Frontmatter is what makes the skill discoverable; the description is
                // the only text the agent sees when deciding to load it, so it names
                // the concrete triggers rather than describing the file.
                sb.AppendLine("---");
                sb.AppendLine("name: " + SkillInstaller.SkillName);
                sb.AppendLine("description: >-");
                sb.AppendLine("  Conventions for working on Jira issues in this Unity project: branch and");
                sb.AppendLine("  commit templates, Unity asset and .meta handling, and how results are");
                sb.AppendLine("  reported back to the Jira Workspace window. Use when a task references a");
                sb.AppendLine("  Jira issue key, or when changing Unity assets, prefabs or scenes.");
                sb.AppendLine("---");
                sb.AppendLine();
                sb.Append(body);

                File.WriteAllText(path, sb.ToString(), new UTF8Encoding(false));

                return new SkillInstallResult { Success = true, Path = path };
            }
            catch (Exception exception)
            {
                return new SkillInstallResult { Success = false, Error = exception.Message };
            }
        }
    }

    /// <summary>
    /// Writes Codex instructions into <c>AGENTS.md</c>.
    /// </summary>
    /// <remarks>
    /// Codex reads project instructions from a file teams also maintain by hand, so
    /// this writer edits only a marker-delimited block. Overwriting the whole file
    /// would be a data-loss bug the first time anyone reinstalled.
    /// </remarks>
    internal sealed class CodexSkillWriter : ISkillWriter
    {
        public string Provider => AgentProvider.Codex;

        public string RelativePath => "AGENTS.md";

        public SkillInstallResult Write(string repositoryRoot, string body)
        {
            try
            {
                string path = Path.Combine(repositoryRoot, RelativePath);
                string existing = File.Exists(path) ? File.ReadAllText(path) : string.Empty;

                File.WriteAllText(path, SkillInstaller.MergeManagedBlock(existing, body),
                    new UTF8Encoding(false));

                return new SkillInstallResult { Success = true, Path = path };
            }
            catch (Exception exception)
            {
                return new SkillInstallResult { Success = false, Error = exception.Message };
            }
        }
    }
}
